services:
  gateway:
    ports:
      - "127.0.0.1:8083:8083"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  user:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  task:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  notifier:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
